name: ðŸ”Ž Code Safety
run-name: Running Code Safety for ${{ github.ref }} on ${{ github.event_name }} ðŸ”Ž
on:
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  check-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-python-uv

      - run: uv run ruff check .

      - uses: ./.github/actions/minimize-uv-cache

  check-formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-python-uv

      - run: uv run ruff format --check .

      - uses: ./.github/actions/minimize-uv-cache

  check-type-safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-python-uv

      - run: uv run pyright

      - uses: ./.github/actions/minimize-uv-cache

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-python-uv

      - run: uv run pytest

      - uses: ./.github/actions/minimize-uv-cache
